CREATE DATABASE games_db;
USE games_db;

CREATE TABLE Games (
    id INT(11) NOT NULL AUTO_INCREMENT,
    gameName VARCHAR(255) COLLATE UTF8_UNICODE_CI NOT NULL,
    console VARCHAR(255) COLLATE UTF8_UNICODE_CI NOT NULL,
    yearPublished INT(11) NOT NULL,
    paid INT(11) NOT NULL
    PRIMARY KEY (id),
    -- UNIQUE KEY email (email)
);